/* eslint-disable no-dupe-keys */
/* eslint-disable import/no-unresolved */
/* eslint-disable global-require */
const images = {
  orderScreen: require('../../assets/images/cendol.png'),
  minus: require('../../assets/images/minus-symbol.png'),
  plus: require('../../assets/images/Vector.png'),
  background: require('../../assets/images/bg.png'),
  backimage: require('../../assets/images/backgroundimage.png'),
  detail: require('../../assets/images/img_detail.png'),
  appLogo: require('../../assets/images/app_logo.png'),
  popup: require('../../assets/images/popup.png'),
  foto: require('../../assets/images/foto.png'),
  fb: require('../../assets/images/fb.png'),
  ig: require('../../assets/images/ig.png'),
  em: require('../../assets/images/em.png'),
  right: require('../../assets/images/right-arrow.png'),
  down: require('../../assets/images/down-arrow.png'),
  home: require('../../assets/images/home.png'),
  saldo: require('../../assets/images/saldo.png'),
  chat: require('../../assets/images/chat.png'),
  profil: require('../../assets/images/profil.png'),
  keranjang: require('../../assets/images/keranjang.png'),
  appLogo: require('../../assets/images/Tavern.png'),
  tokennotfound: require('../../assets/images/tokennotfound.png'),
  // back: require('../../assets/images/back.png'),
  // checkBoxOn: require('../../assets/images/checkbox_on.png'),
  // checkBoxOff: require('../../assets/images/checkbox_off.png'),
  // close: require('../../assets/images/close.png'),
  // dropdown: require('../../assets/images/ic_dropdown.png'),
  //  faceSad: require('../../assets/images/face_sad.svg'),
  // login: require('../../assets/images/login.png'),
  // modalCamera: require('../../assets/images/modal_camera.png'),
  // modalGallery: require('../../assets/images/modal_gallery.png'),
  // noConnection: require('../../assets/images/no_connection.png'),
  // passOff: require('../../assets/images/padlock_off.png'),
  // passOn: require('../../assets/images/padlock_on.png'),
  // search: require('../../assets/images/ic_search.png'),
  // userOff: require('../../assets/images/user_off.png'),
  // userOn: require('../../assets/images/user_on.png'),
  first: require('../../assets/images/firstslide.png'),
  second: require('../../assets/images/secondslide.png'),
  third: require('../../assets/images/thirdslide.png'),
  pp: require('../../assets/images/pp.png'),
  voucher: require('../../assets/images/voucher.png'),
  help: require('../../assets/images/information.png'),
  about: require('../../assets/images/about.png'),
  signout: require('../../assets/images/signout.png'),
  camera: require('../../assets/images/camera.png'),
  background: require('../../assets/images/bg.png'),
  cart: require('../../assets/images/cart.png'),
  androidLogo: require('../../assets/images/android.png'),
  icoBack: require('../../assets/images/ic-back.png'),
  icoSearch: require('../../assets/images/ic-search.png'),
  icoCloseGrey: require('../../assets/images/ic-close-grey.png'),
  category1: require('../../assets/images/category1.png'),
  category2: require('../../assets/images/category2.png'),
  category3: require('../../assets/images/category3.png'),
  category4: require('../../assets/images/category4.png'),
  category5: require('../../assets/images/category5.png'),
  category6: require('../../assets/images/category6.png'),
  categoryall: require('../../assets/images/allcategory.png'),
  categoryRecom: require('../../assets/images/categoryrekomended.png'),
  topupactive: require('../../assets/images/topupikon.png'),
  topupdisable: require('../../assets/images/topupdisable.png'),
  checkoutactive: require('../../assets/images/chatactive.png'),
  checkoutdisable: require('../../assets/images/chatdisable.png'),
  akunactive: require('../../assets/images/akunactive.png'),
  akundisable: require('../../assets/images/akundisable.png'),
  voucher1: require('../../assets/images/voucher1.png')
};

export default images;
